name: 'Get and cache dependencies'
description: 'Cache node dependencies for the project for use between steps'
runs:
  using: composite
  steps:

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: dependencies-node-modules-${{ hashFiles('**/package-lock.json')}}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci

