name: 'Build | Node.js'

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches: [ $default-branch ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:

  lint-test-build:
    uses: ./.github/workflows/lint-test-build.yml
    with:
      is-deploy: false

